create table if not exists public.provider_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

create index if not exists provider_events_provider_received_at_idx
  on public.provider_events (provider, received_at desc);

alter table public.provider_events enable row level security;
